apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_key
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.42
  ports:
  - name: ftp
    port: 20
    protocol: TCP
    targetPort: 20
  - name: ftp2
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftp3
    port: 21000
    protocol: TCP
    targetPort: 21000
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - name: ftp
          containerPort: 20
        - name: ftp2
          containerPort: 21
        - name: ftp3
          containerPort: 21000