apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_key
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.49
  ports:
  - name: http
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 5050